### ISSUE TITLE
repos are old

### ISSUE THREAD

**Issue by gstaples** [geerlingguy/ansible-role-filebeat#13]
The filebeat installed by this role is rather ancient.  I've updated the repos on my local copy of this role. 

repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'

baseurl=https://artifacts.elastic.co/packages/5.x/yum

**Comment by gstaples** [comment]
Also, "depdency" :)

**Comment by tdac** [comment]
Hi - just to note I've already put a Pull Request for the Repo - https://github.com/geerlingguy/ansible-role-filebeat/pull/11 and the typo https://github.com/geerlingguy/ansible-role-filebeat/pull/8 ;-)

**Comment by geerlingguy** [comment]
Repos should be fixed now, in the latest role version. Thanks for reporting!
