### ISSUE TITLE
apt-key for elastic repository is fetched even if it's already imported

### ISSUE THREAD

**Issue by verboEse** [geerlingguy/ansible-role-filebeat#27]
We encounter an issue fetching the key for the elastic repository for Debian. Our servers need a proxy setting, but the apt_key module does not support providing proxy configuration. apt-key itself has no configuration file to configure a proxy, either.
Until this is fixed, we would like to import the key manually (or by a script that gets called by ansible).
Further we should provide the elastic apt-key ID (46095ACC8548582C1A2699A9D27D666CD88E42B4) in setup-Debian.yml, so it does not get fetched again when its already there. This also will reduce web calls for all other installations.

**Comment by verboEse** [comment]
I just added pull request #29 for this ...

**Comment by geerlingguy** [comment]
Fixed in #29 - thanks!
