### ISSUE TITLE
Adapt new pipeline configuration for filebeats 6.3

### ISSUE THREAD

**Issue by secretworry** [geerlingguy/ansible-role-filebeat#32]
`Prospectors` are deprecated and  renamed to `inputs` in 6.3.0 ([Release note for 6.3.0](https://www.elastic.co/guide/en/beats/libbeat/6.3/release-notes-6.3.0.html) or more specifically the [PR](https://github.com/elastic/beats/pull/6078)), and further removed in 7.0.
So some version checking might be required in the `filebeat.yml.j2`.

**Comment by geerlingguy** [comment]
I'll be updating the role for 7.x and dropping `prospectors` entirely, and it will be in a new major version of the role.

**Comment by geerlingguy** [comment]
See #32 as well.
