### ISSUE TITLE
Error including SSL certificate 

### ISSUE THREAD

**Issue by tdac** [geerlingguy/ansible-role-filebeat#4]
Ansible 2.2.1.0 (Ubuntu 16.04) 

When running ansible-role-filebeat with an filebeat_ssl_dir set - I get the following error:

`TASK [geerlingguy.filebeat : Ensure Filebeat SSL key pair directory exists.] ***`
`fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'filebeat_ssl_key_file' failed. The `
`error was: error while evaluating conditional (filebeat_ssl_key_file): 'filebeat' is undefined\n\nThe error `
`appears to have been in '/etc/ansible/roles/geerlingguy.filebeat/tasks/config.yml': line 11, column 3, but `   `may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to `
`   be:\n\n\n- name: Ensure Filebeat SSL key pair directory exists.\n  ^ here\n"}`

everything is pretty much standard - with my vars/ssl.yml configured like this: 

`filebeat_ssl_dir: '/etc/pki/graylog2'`
`filebeat_ssl_certificate_file: 'filebeat.crt'`
`filebeat_ssl_key_file: 'filebeat.key'`

If I edit config.yml manually and alter the "when" on the `Ensure Filebeat SSL key pair directory exists.` step from `when: filebeat_ssl_key_file` to `when: filebeat_ssl_key_file is defined`  then the script completes correctly. 

Have I hit a regression bug - or am I doing something fundamentally silly? ;-)

**Comment by sebkouba** [comment]
I had the same problem. I'm pretty sure is should say "is defined".

**Comment by runtman** [comment]
I had similiar issues on the logstash rule, I believe it wants a physical file in /role/files/ to copy from. This wasn't ideal for me, so I did the same when remove the "when"

**Comment by mishac** [comment]
I added a pr at #19

**Comment by IronCore864** [comment]
Same here. Still not merged?
