### ISSUE TITLE
Allow to skip config.yml

### ISSUE THREAD

**Issue by tomyam1** [geerlingguy/ansible-role-filebeat#6]
I prefer to generate the config file myself. 
Will you accept a PR for skipping the config tasks, e.g. with `filebeat_skip_config` variables whose default value is `no`?

**Comment by geerlingguy** [comment]
Yes—but I like the reverse for a var, so default:

`fieldbeat_create_config: true`

Then you can disable the role's config management by setting that to false/no

**Comment by tomyam1** [comment]
Thanks! Really love your roles.

Done in PR #7

**Comment by geerlingguy** [comment]
Thank _you_—this makes it a lot more flexible, since it would be really hard to satisfy most people's use cases with a generic filebeat config.
